# simple-pipeline.yml

resources:
  - name: simple-repo
    type: git
    source:
      uri: github.com/mareedu868/concourse.git
      branch: main

jobs:
  - name: simple-job
    plan:
      - get: simple-repo
        trigger: true
      - task: run-script
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: alpine
          inputs:
            - name: simple-repo
          run:
            path: /bin/sh
            args:
              - -c
              - "echo 'Running a simple script!' && cd simple-repo && ./run.sh"
